[project]
name = "usfds-infra"
version = "0.1.0"
description = "Infrastructure implementations for USFDS"
authors = [
    {name = "pqkkkk", email = "22120174@student.hcmus.edu.vn"}
]
readme = "README.md"
requires-python = ">=3.12"

[tool.poetry]
packages = [{include = "usfds_infra", from = "src"}]

[tool.poetry.dependencies]
python = "^3.12"
usfds-core = {path = "../usfds-core", develop = true}

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
